### ISSUE TITLE
xhgeo.com

### ISSUE THREAD

**Issue by spirillen** [brijrajparmar27/host-sources#2]
Redirects straight to xhamster

https://github.com/brijrajparmar27/host-sources/blob/6f575e63f4c678fdac5b92d39dcfe3e3a8624584/Porn/hosts#L5

```
curl -I 'https://xhgeo.com'
HTTP/2 302 
server: nginx
date: Wed, 29 Sep 2021 18:53:59 GMT
content-type: text/html; charset=UTF-8
location: https://xhamster.com?xhms_pro=1
```

```
curl -I 'https://amp.xhgeo.com'
HTTP/2 302 
server: nginx
date: Wed, 29 Sep 2021 18:54:39 GMT
content-type: text/html; charset=UTF-8
location: https://amp.xhamster.com?xhms_pro=1
```

**Comment by brijrajparmar27** [comment]
blocking xhamster hosts somehow doesn't block the site from proxies from amp on mobile devices, the contents for the same can be accessed without actually visiting the site, the whole Accelerated Mobile Pages Framework is kinda weird, hence the entries that point to the same domain.

**Comment by spirillen** [comment]
Sounds weird, but with goo.. you never know, they never read the RFC's
