### ISSUE TITLE
amp.xhamster

### ISSUE THREAD

**Issue by spirillen** [brijrajparmar27/host-sources#4]
`amp.xhamster*` Already listed in https://github.com/Clefspeare13/pornhosts via https://mypdns.org/search?scope=issues&search=amp.xhamster&sort=created_asc&group_id=20&project_id=2

https://github.com/brijrajparmar27/host-sources/blob/6f575e63f4c678fdac5b92d39dcfe3e3a8624584/Porn/hosts#L2-L4

**Comment by brijrajparmar27** [comment]
Clefspeare13's hosts repo is killed by github.

**Comment by spirillen** [comment]
> Clefspeare13's hosts repo is killed by github.

Yeah. thanks god I had the real repo (as the only maintainer) :wink:  It's moved here: https://mypdns.org/clefspeare13/pornhosts

The only thing that didn't come with the movement is the issues 


However it is still feeded from https://mypdns.org/my-privacy-dns/porn-records as it have been for over a year
