### ISSUE TITLE
bonertraffic12.mobi

### ISSUE THREAD

**Issue by spirillen** [brijrajparmar27/host-sources#6]
`bonertraffic12.mobi` is ad domain, not porn: https://mypdns.org/my-privacy-dns/matrix/-/issues/3057

https://github.com/brijrajparmar27/host-sources/blob/6f575e63f4c678fdac5b92d39dcfe3e3a8624584/Porn/hosts#L8

**Comment by brijrajparmar27** [comment]
I see thanks for letting me know, will move it to appropriate list.

**Comment by spirillen** [comment]
Well it was the main idea behind my suggestion of collaboration in https://github.com/brijrajparmar27/host-sources/issues/1 but you turned it down.

**Comment by brijrajparmar27** [comment]
sorry about that, the thing is i have only 150~ hosts that isn't much, on top of that i have no fixed time at which i update them either, sometimes one a week, sometimes once a month, figured i won't be of much use to your project.

**Comment by spirillen** [comment]
Well I would actually say you have ~ 300 reasons to participate and you wrote something about you could code in python which I can't... 

For how much you can contribute is less important than the quality of what is contributed. There is a reason the lists are handmade and not just punched in bulks or even done over scripts from other lists. Where I could mention several HUGE lists, but with about 80% FP's.

My offer still stands.

**Comment by brijrajparmar27** [comment]
I'm ready to contribute but how does this work? i mean my list is already included in steven black's list, do you have a separate list?

**Comment by spirillen** [comment]
The main lists are in `https://mypdns.org/my-privacy-dns/porn-records` that is where all the issues is, from there I have a local bash script I use to push to all the repos.

removal from:
- my-privacy-dns/matrix
- Import-External-Sources/pornhosts
- rpz.mypdns.cloud (RPZ zone)

Adding to:
- clefspeare13/pornhosts (hosts format only)
- my-privacy-dns/porn-records (Raw formatted lists to build any blacklist format)
- adult.mypdns.cloud (RPZ zone)

That's actually just about that, everything you find or even can build of scripts helping in this process would be superior, especially for a commit script for the public (have an open idea [here](https://mypdns.org/my-privacy-dns/porn-records/-/issues/59))

You can see an example here `https://mypdns.org/my-privacy-dns/porn-records/-/issues/1396` of how it optimally should be looking like as it have all the reasons for one domain = one issue. It is imported from the old issue board, it have changes to the domain, it have refs to other issues and those information's are gathered one place :smiley: 

Depending on the time you have, I will contributing to move your list to PR (starting from the bottom of the list)

For the SB/hosts... hmm I'm open for suggestions, but I would for sure recommend he merged `https://github.com/StevenBlack/hosts/pull/1784` and as `@benbalter` told him, he shall not be so scared of doing it. You can read the published version of the issue here: [TOS Review: mypdns/porn-records #1323585](https://mypdns.org/my-privacy-dns/porn-records/-/issues/1347)
